version: '3.1'

volumes:
  scraping_jobs:

services:
  scraping_jobs_db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: scraping_jobs_db
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: password
    volumes:
      - scraping_jobs:/var/lig/postgresql/data
    ports:
      - "5432:5432"

#  app:
#    image: olehdenkovych/scraping-jobs-app:latest
#    depends_on:
#      - scraping_jobs_db
#    environment:
#      SPRING_DATASOURCE_URL: 'jdbc:postgresql://scraping_jobs_db:5432/scraping_jobs_db'
#    volumes:
#      - scraping_jobs:/var/lig/postgresql/data
#    ports:
#      - "8081:8081"