spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/scraping_jobs_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: developer
    password: password
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate

  application:
    name: ScrapingJobs

server:
  port: 8081

springdoc:
  api-docs:
    path: /swagger/api-docs
  swagger-ui:
    path: /swagger/swagger-ui.html